
//EVEN THO SERVICES DONT HAVE DTOS IM CREATING ONE BECAUSE NEED TO PUT THE MEDIACATEGORY ENUM SOMEWHERE
//AND LETS NOT UPDATE THE PREEXISITNG VALUES IN THIS ENUM THEY CANT BE STRICTLY CHANGED OTHERWISE THE R2 STORAGE STRUCTURE FUCKS UP
public enum MediaCategory
{
    ProfilePicture,
    Post,
    VideoPost
}